optimizer:
  optimizer: momentum
  lr_init: 0.01  # initial learning rate (SGD=1E-2, Adam=1E-3)
  weight_decay: 0.0005  # optimizer weight decay 5e-4
  momentum: 0.937  # SGD momentum/Adam beta1
  nesterov: True # update gradients with NAG(Nesterov Accelerated Gradient) algorithm
  loss_scale: 1.0 # loss scale for optimizer
  warmup_epochs: 3  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  min_warmup_step: 1000 # minimum warmup step
  group_param: yolov7 # group param strategy
  start_factor: 1.0
  end_factor: 0.01

loss:
  name: YOLOv7Loss
  loss_item_name: ['box', 'cls', 'obj'] # branch name returned by loss
  box: 0.05  # box loss gain
  cls: 0.5  # cls loss gain
  cls_pw: 1.0  # cls BCELoss positive_weight
  obj: 1.0  # obj loss gain (scale with pixels)
  obj_pw: 1.0  # obj BCELoss positive_weight
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  anchor_t: 4.0  # anchor-multiple threshold
  label_smoothing: 0.0 # label smoothing epsilon
  loss_ota: 1 # use ComputeLossOTA, use 0 for faster training
  use_aux: 0 # not use aux loss on p5/tiny train

data:
  num_parallel_workers: 4

  train_transforms:
    multi_imgs_transforms:
      - Mosaic: { mosaic_prob: 1.0, copy_paste_prob: 0.0, translate: 0.1, scale: 0.5, target_size: 640 }
      - MixUp: { prob: 0.05, alpha: 8.0, beta: 8.0, mosaic_needed: True }
      - PasteIn: { prob: 0.05, target_size: 640 }
    single_img_transforms:
      - RandomHSV: { hgain: 0.015, sgain: 0.7, vgain: 0.4 }
      - RandomFlip: { prob: 0.5 }
      - NormalizeBox: { xyxy2xywh: True }
      - NormalizeImage: { is_scale: True, norm_type: none }
      - TransposeImage: { bgr2rgb: True, hwc2chw: True }
    batch_imgs_transform:
      BatchLabelsPadding: { padding_size: 160, padding_value: -1 }

  eval_transforms:
    single_img_transforms:
      - Resize: { target_size: 640, keep_ratio: True }
      - LetterBox: { target_size: 640 }
      - NormalizeBox: { xyxy2xywh: True }
      - NormalizeImage: { is_scale: True, norm_type: none }
      - TransposeImage: { bgr2rgb: True, hwc2chw: True }

img_size: 640 # image sizes
