__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s.yaml'
]

# difference with s
# 1. backbone
# 2. depth and width

network:
  depth_multiple: 1.0
  width_multiple: 1.0

  backbone:
    # [from, number, module, args]
    [
      [ -1, 1, ConvNormAct, [ 32, 3, 1, act=nn.LeakyReLU(0.1) ] ],                  # 0, stem.0,
      [ -1, 1, ConvNormAct, [ 64, 3, 2, act=nn.LeakyReLU(0.1) ] ],                  # 1, stem.1, /2
      [ -1, 1, Bottleneck, [ 64, act=nn.LeakyReLU(0.1) ] ],                         # 2, stem.2,

      [ -1, 1, ConvNormAct, [ 128, 3, 2, act=nn.LeakyReLU(0.1) ] ],                 # 3, dark2.0, /4
      [ -1, 2, Bottleneck, [ 128, act=nn.LeakyReLU(0.1) ] ],                        # 4, dark2.1,

      [ -1, 1, ConvNormAct, [ 256, 3, 2, act=nn.LeakyReLU(0.1) ] ],                 # 5, dark3.0, /8
      [ -1, 8, Bottleneck, [ 256, act=nn.LeakyReLU(0.1) ] ],                        # 6, dark3.1,

      [ -1, 1, ConvNormAct, [ 512, 3, 2, act=nn.LeakyReLU(0.1) ] ],                 # 7, dark4.0, /16
      [ -1, 8, Bottleneck, [ 512, act=nn.LeakyReLU(0.1) ] ],                        # 8, dark4.1,

      [ -1, 1, ConvNormAct, [ 1024, 3, 2, act=nn.LeakyReLU(0.1) ] ],                # 9, dark5.0, /32
      [ -1, 4, Bottleneck, [ 1024, act=nn.LeakyReLU(0.1) ] ],                       # 10, dark5.1,
      [ -1, 1, ConvNormAct, [ 512, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 11, dark5.2,
      [ -1, 1, ConvNormAct, [ 1024, 3, 1, act=nn.LeakyReLU(0.1) ] ],                # 12, dark5.3,
      [ -1, 1, SPPF, [ 512, act=nn.LeakyReLU(0.1) ] ],                              # 13, dark5.4
      [ -1, 1, ConvNormAct, [ 1024, 3, 1, act=nn.LeakyReLU(0.1) ] ],                # 14, dark5.5
      [ -1, 1, ConvNormAct, [ 512, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 15, dark5.6     (small)
    ]


  head:
    [
      [ -1, 1, ConvNormAct, [ 256, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 16, out1_cbl,
      [ -1, 1, Upsample, [ None, 2, 'nearest' ] ],                                  # 17, upsample0, /16
      [ [ -1, 8 ], 1, Concat, [ 1 ] ],                                              # 18, concat,
      [ -1, 1, ConvNormAct, [ 256, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 19, out1.0,
      [ -1, 1, ConvNormAct, [ 512, 3, 1, act=nn.LeakyReLU(0.1) ] ],                 # 20, out1.1,
      [ -1, 1, ConvNormAct, [ 256, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 21, out1.2,
      [ -1, 1, ConvNormAct, [ 512, 3, 1, act=nn.LeakyReLU(0.1) ] ],                 # 22, out1.3,
      [ -1, 1, ConvNormAct, [ 256, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 23, out1.4,   (middle)

      [ -1, 1, ConvNormAct, [ 128, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 24, out2_cbl,
      [ -1, 1, Upsample, [ None, 2, 'nearest' ] ],                                  # 25, upsample1, /8
      [ [ -1, 6 ], 1, Concat, [ 1 ] ],                                              # 26, concat,
      [ -1, 1, ConvNormAct, [ 128, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 27, out2.0,
      [ -1, 1, ConvNormAct, [ 256, 3, 1, act=nn.LeakyReLU(0.1) ] ],                 # 28, out2.1,
      [ -1, 1, ConvNormAct, [ 128, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 29, out2.2,
      [ -1, 1, ConvNormAct, [ 256, 3, 1, act=nn.LeakyReLU(0.1) ] ],                 # 30, out2.3,
      [ -1, 1, ConvNormAct, [ 128, 1, 1, act=nn.LeakyReLU(0.1) ] ],                 # 31, out2.4,   (large)

      [ [ 31, 23, 15 ], 1, YOLOXHead, [ nc, stride, is_standard_backbone=False, act=nn.LeakyReLU(0.1) ] ],       # 32, detection head
    ]
