__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s-2nd.yaml'
]

weight: ./runs/2023.04.24-09:35:19/weights/yolox-s-285_1848.ckpt
ema_weight: ./runs/2023.04.24-09:35:19/weights/EMA_yolox-s-285_1848.ckpt

optimizer:
  checkpoint_path: ./runs/2023.04.24-09:35:19/weights/optim_yolox-s.ckpt

network:
  depth_multiple: 1.0
  width_multiple: 1.0
